### PR TITLE
fix(us): require space-separated street suffix in address regex

### LINKED ISSUE #68: US address regex false positive on German word 'ist' (and other St-ending words)
## Summary

The US address pattern `(?i)\d+\s+[A-Za-z\s]+(?:Street|St|Avenue|Ave|...)\b` produces false positives on German text containing the word "ist" (meaning "is"), because "ist" decomposes as `[A-Za-z\s]+` matching "i" and `St\b` matching "st".

## Reproduction

```
Input:  "Steuer-ID 65929970489 ist korrekt."
Result: "65929970489 ist" matched as ADDRESS (type PII_ADDRESS)

Input:  "Code 12345 ist falsch."
Result: "12345 ist" matched as ADDRESS

Input:  "SVNR 12151385A123 ist falsch."  
Result: "123 ist" matched as ADDRESS (trailing digits of SVNR + "ist")
```

Any German sentence with `\d+` followed by "ist" will trigger this.

## Impact

- German text processed with DE+US packs enabled gets spurious ADDRESS tokens
- The false ADDRESS match can consume digits that belong to other patterns (e.g., trailing digits of a Steuer-ID)
- Low confidence (0.75) means it goes to AI verification when UseAI=true, adding unnecessary Ollama queries

## Other affected words

Any word ending in a US street suffix (case-insensitive):
- German "ist" → "St"
- German "Bist" → "St" 
- "exist" → "St"
- "Kunst" → "St" (if preceded by digits)
- Potentially: "erst", "wurst", "Durst", etc.

## Proposed fix

Options (in order of preference):

1. **Require minimum local-part length**: Change `[A-Za-z\s]+` to `[A-Za-z\s]{3,}` or require at least one space + one alpha word before the suffix. This prevents single-character "street names."

2. **Require the suffix to be a standalone word**: Use `\b(?:Street|St|Avenue|...)\b` with a preceding `\s` to ensure the suffix is space-separated from the "street name."

3. **Negative lookbehind for common false positives**: Add `(?<!\bist)` etc., though this is fragile.

Example fix for option 2:
```go
// Before
Re: regexp.MustCompile(`(?i)\d+\s+[A-Za-z\s]+(?:Street|St|Avenue|...)\b`)

// After — require suffix to be space-preceded
Re: regexp.MustCompile(`(?i)\d+\s+[A-Za-z]+(?:\s+[A-Za-z]+)*\s+(?:Street|St|Avenue|...)\b`)
```

## Verified with integration tests

Confirmed in both DE and GLOBAL test reports (21 + 27 cases). The "ist" false positive was discovered when running German-language test content through the full pipeline. See PR #66 test report comments.

## Labels

bug, anonymizer, US, cross-pattern

### PR DESCRIPTION
**Pull request by laplaque**
## Summary

- **Fixes #68** — US address regex false positive on German word "ist" (and other words ending in street suffixes like "Kunst", "Durst", "erst", "Bist")
- Changed `[A-Za-z\s]+` to `[A-Za-z]+(?:\s+[A-Za-z]+)*\s+` in the `address_us` regex so the street-type suffix must be a standalone, space-preceded word
- Added negative test cases for German false positives and additional positive test cases for short legitimate street names ("321 Oak St", "10 A St", "5 B Ave")

## Root Cause

The regex `(?i)\d+\s+[A-Za-z\s]+(?:Street|St|...)` allowed `[A-Za-z\s]+` to match a single character like "i", then "st" matched the `St` suffix. Any German sentence with `\d+ ist` triggered a false ADDRESS match.

## Fix

Replaced the street-name capture group so it requires at least one alpha word followed by a mandatory space before the suffix:

```
Before: \d+\s+[A-Za-z\s]+(?:Street|St|...)
After:  \d+\s+[A-Za-z]+(?:\s+[A-Za-z]+)*\s+(?:Street|St|...)
```

## Test Plan

- [x] All existing US address positive tests pass ("123 Main Street", "456 Elm Ave", "789 Oak Boulevard")
- [x] New positive tests for short street names: "321 Oak St", "10 A St", "5 B Ave"
- [x] New negative tests for German false positives: "ist", "Kunst", "Durst", "erst", "Bist"
- [x] Full `go test -race ./...` passes with zero failures
- [x] Packs coverage: 97.6% (threshold: 95%)

## Existing Issues

- `make check` fails on clean checkout due to golangci-lint being built with Go 1.25, which is lower than the targeted Go 1.26.1 — pre-existing, not introduced by this PR

https://claude.ai/code/session_01GtNbHBY1dmoifVzoSx8Zhh

### CODE REVIEW

File: internal/anonymizer/packs/us.go [hunk 1]
```diff
@@ -89,7 +89,7 @@ func init() {
 		Entry{
 			Name:       "address_us",
 			Pack:       "US",
-			Re:         regexp.MustCompile(`(?i)\d+\s+[A-Za-z\s]+(?:Street|St|Avenue|Ave|Road|Rd|Boulevard|Blvd|Lane|Ln|Drive|Dr|Court|Ct)\b`),
+			Re:         regexp.MustCompile(`(?i)\d+\s+[A-Za-z]+(?:\s+[A-Za-z]+)*\s+(?:Street|St|Avenue|Ave|Road|Rd|Boulevard|Blvd|Lane|Ln|Drive|Dr|Court|Ct)\b`),
```
Comment (laplaque) [inline internal/anonymizer/packs/us.go]: **HIGH:** The regex fix here is correct, but `anonymizer.go` `compilePatterns()` (line ~205) still has the old broken pattern:
```go
{`(?i)\d+\s+[A-Za-z\s]+(?:Street|St|Avenue|Ave|Road|Rd|Boulevard|Blvd|Lane|Ln|Drive|Dr|Court|Ct)\b`, PIIAddress, 0.75},
```
The legacy path is used when `EnabledPacks` is empty — which includes all existing integration tests via `newTestAnonymizer()`. The fix is incomplete until the legacy regex is also updated.

Additionally, `[A-Za-z]+` for street name segments won't match numeric ordinals ("5th", "42nd", "3rd"). Addresses like `789 42nd Street` are false negatives. This is a pre-existing limitation (the old regex had it too), but worth documenting with a code comment now that the regex is being revised.
